apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commerce2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Substituir pela URL real do repo apos o push
    repoURL: https://github.com/GabArtista/commerce2.git
    targetRevision: main
    path: k8s/base
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
